import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import "@liveblocks/react-ui/styles.css";

const outfit = Outfit({
  subsets: ["latin"],
  
});

export const metadata = {
  title: "Microsoft Loop Clone",
  description: "Generated by Raj Singh",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
      <html lang="en">
        <body className={`${outfit.className}`}>
          {children}
          <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  );
}
